### ISSUE TITLE
Documentation for RC Command

### ISSUE THREAD

**Issue by tgb20** [AlexanderGranhof/tello-drone#4]
I have been working with your library for a little while and really like it, but there is little documentation on how to get the RC command to work. Its mentioned in your code, but I can't quite figure out how to interface with it. Any suggestions would be helpful.

**Comment by AlexanderGranhof** [comment]
I've double checked and i see now i actually have missed setting limits on the rc command so you can actually never send it without it failing to validate. Ill have a look at it and see if i can add more full documentation on each command.

Ill see if i can get it done by this weekend!

**Comment by tgb20** [comment]
Ok sounds good thanks!

And if you are building a priority for changes, the RC mode working I think is more important than the documentation as most of it is explained in the Tello guide.

**Comment by AlexanderGranhof** [comment]
You should be able to use the rc command now.
```js
await drone.send("rc", { a: 50, b: 60, c: 70, d: 80 })
```

I need to look more into the documentation, i see now that the documentation differs alot between 1.3 and 2.0. And i cant find any information on which documentation version you should refer to, such as if you have a specific firmware version. When i tested the 2.0 specs with the latest firmware version a while back, it didn't work. But ill look into it.

**Comment by tgb20** [comment]
Do you have a normal Tello or a Tello EDU? Seems 2.0 is only designed for EDU models.

**Comment by AlexanderGranhof** [comment]
I believe i have a normal tello, bought it myself. But if 2.0 is for EDU then i understand. Interesting nonetheless, ill look into to it. But it the RC command should be working now in 3.0.2.
