### ISSUE TITLE
Error dgram

### ISSUE THREAD

**Issue by ArthurVerstraete** [AlexanderGranhof/tello-drone#9]
Hello,

I'm using your npm package for my react-native app and got stuck with this error. Can someone please help me?
![image](https://user-images.githubusercontent.com/36663371/78392485-96239c00-75e8-11ea-9302-c243d1ca77d9.png)

**Comment by AlexanderGranhof** [comment]
Hey,
dgram is a native nodejs package. My package is meant to run as a "backend process" using node. You might need to create an API in node between your react-native app to communicate with the drone.

Does that answer your question?
